version: "3"

services:
    php:
        build: docker/php
        volumes:
            - ./:/app
        ports:
            - "8000:8000"
        restart: unless-stopped
        depends_on:
            - mysql

    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "33062:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=kEdrecA4_xu4
